### ISSUE TITLE
Not finding .json files in default directory .appdata/tweets/

### ISSUE THREAD

**Issue by ben-en** [Outernet-Project/librarian-twitter#4]
Unrelated to #3. 

Twitter seems to not be checking for tweets regularly. When i looked in my .appdata/tweets/ directory, it was fully populated. When i restarted librarian, the log was filled with messages from twitter importing the files.

**Comment by foxbunny** [comment]
Can you clarify under what circumstances this happens?

**Comment by ben-en** [comment]
Not really.

It seems that tweets are imported at least once, however it seems that .json files are not picked up after the first run. My Lighthouse sat for a few days accumulating tweets. When i restarted it, all the tweets were found and imported.

I'll look into fixing it today after i fix/give up on fixing that ugly absolute path in pageshot.

**Comment by foxbunny** [comment]
This is probably related to FSAL issue.

**Comment by ben-en** [comment]
Must've been related to the FSAL issue as the previous comment indicates, haven't seen the issue since.
